---
title: "Week4"
author: "Skylar Ciccolini"
date: "2025-09-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pre-class

```{r}
# try and make a plot

# Set up
library(tidyverse)

ag <- read_csv("Data/agronomic_yields.csv")



ggplot() +
  geom_smooth(data = ag, aes(x = Year, y = Yield_kg_ha,
                             color = Crop, fill = Crop)) +
  labs(x = "Date", y = "Yield (kg/ha)") +
theme(axis.text.x = element_text(angle = 90)) +
  scale_color_brewer(palette = "YlGrBu") +
  scale_fill_brewer(palette = "YlGrBu")


# factor stuff

library(gapminder)

data("gapminder")

gapminder$country

levels(gapminder$country) ## check levels of factor

countries <- as.character(gapminder$country) ## convert to character to alphabetize

## going from factor to number will just convert factor levels to numbers 1,2,3 etc, 
## not whatever the factor value is

## go from factor -> character -> numeric
as.numeric(as.character(gapminder$country))

# fcns for dealing with factors
levels()
reorder()
fct_reorder()
fct_relevel()

```


## Spatial Data

### sp

```{r}

library(spData)
library(sp)


data("elect80")

glimpse(elect80)

class(elect80)

# can index directly into the variables w/o going through the data slot
elect80$FIPS


```

Some Plotting

```{r}

#points of coord points in df
sp::plot(elect80, pch = 20, cex = 0.5, col = "pink")

# what is the CRS?
elect80@proj4string


```



### sf

```{r}

library(sf)

data("us_states")

class(us_states)

glimpse(us_states)

# whats the CRS?
st_crs(us_states)

```

Some Plotting

```{r}

plot(us_states[ ,1]) ## just plot the first col

plot(us_states) ## plot all cols

# plot the boundaries
plot(st_geometry(us_states))



```


Summarizing

```{r}
# total pop by region in 2015
sum <- us_states |> 
  group_by(REGION) |> 
  summarise(TotalPop = sum(total_pop_15))

ggplot() +
  geom_sf(data = sum, aes(fill =TotalPop))
```


## Actual Data

```{r}

library(tigris) ## pulls in official boundaries from census data

# read in MO county data
counties <- counties(state = "KS")

class(counties)

glimpse(counties)

# plot
plot(counties[ ,1])

ggplot() +
  geom_sf(data = counties)

# check crs
st_crs(counties)

```


### Lets merge things

```{r}
# read in some data
bea <- read_csv("Data/KS_BEA.csv")



```


## Tidy the data (from Week3)

```{r}
bea_clean <- bea |> 
  filter(GeoFIPS != "Note: See the included footnote file." | 
           GeoFIPS != "CAGDP2: Gross domestic product (GDP) by county and metropolitan area 1/" |
           GeoFIPS != "Last updated: December 9, 2020 -- new statistics for 2019, revised statistics for 2001-2018." |
           GeoFIPS != "Source: U.S. Department of Commerce / Bureau of Economic Analysis / Regional Economic Accounts") 

bea_tidy <- bea_clean |> 
  pivot_longer(cols = 9:27,
                        names_to = "Year",
                        values_to = "Value")


bea_tidier <- bea_tidy |> 
  pivot_wider(names_from = Description,
              values_from = Value)


## need to add a line so that it recognizes that there is a unique combo of location and year

## need to do this when your dataset has a lot of built in redundancies

bea_tidier <- bea_tidy |> 
  pivot_wider(id_cols = c("GeoFIPS", "Year"), ## list of unique cols
              names_from = Description,
              values_from = Value)

# check for NAs
colSums(is.na(bea_tidier)) ## YAY! no NAs here

## Welp, this doesn't work

#bea_clean <- bea_tidier |> 
  #mutate_at(., 
            #vars = ("Year":'Private services-providing industries 3/',
            #~as.numeric()))

bea_clean <- bea_tidier |> 
  mutate(across(Year:`Private services-providing industries 3/`,
         ~as.numeric(.)))


glimpse(bea_clean)
```

Clean the GEOFIPS

```{r}

bea_cleaner <- bea_clean |> 
  mutate(GEOID = str_extract(GeoFIPS, "\\d+")) ## str_extract removes parts of string from each value

bea_cleaner$GEOID

```


## Join Data

```{r}

bea_sf <- left_join(counties, bea_cleaner, 
                    by = c("GEOID")) ## left side should be spatial data, right side is attributes

glimpse(bea_sf)

class(bea_sf)

```


### Plotting

```{r}

ggplot() +
  geom_sf(data = bea_sf, aes(fill = `All industry total`))


# normalize data so you aren't just showing the pop effects
ggplot() +
  geom_sf(data = bea_sf, aes(fill = log(`All industry total`, 10)))

# one year only instead of all of the years
ggplot() +
  geom_sf(data = bea_sf |> 
            filter(Year == 2001), aes(fill = log(`All industry total`, 10)))

# show all the years but broken apart into different plots
ggplot() +
  geom_sf(data = bea_sf, aes(fill = log(`All industry total`, 10))) +
  facet_wrap(~Year)



```




















